### ISSUE TITLE
extra keys not allowed @ data['icon']

### ISSUE THREAD

**Issue by disrupted** [chrom3/kodi_notification#1]
I can't set a custom icon using an url. This is the error message I see in the HA logs.
```
2017-11-29 00:15:09 ERROR (MainThread) [homeassistant.core] Invalid service data for notify.kodi: extra keys not allowed @ data['icon']. 
Got 'https://community-home-assistant-assets.s3-us-west-2.amazonaws.com/optimized/2X/6/6a99ebb8d0b585a00b407123ff76964cb3e18780_1_500x500.png'
```

I am calling this action from an automation:
```yaml
  - service: notify.kodi
    data:
      icon: "http://myurl.com/custom_icon.png" # or "warning"
      message: >
        my notification text
```
